"""rename tables

Revision ID: fe9eed6d812f
Revises: 7d9871ef8afa
Create Date: 2019-04-11 15:33:25.591043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe9eed6d812f'
down_revision = '7d9871ef8afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE dpo.model_checksum RENAME TO execution_model')
    op.execute('ALTER TABLE dpo.data_pipeline_execution RENAME TO execution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE dpo.execution RENAME TO data_pipeline_execution')
    op.execute('ALTER TABLE dpo.execution_model RENAME TO model_checksum')
    # ### end Alembic commands ###
